### ISSUE TITLE
Option to connect to source or destination database using ssl

### ISSUE THREAD

**Issue by nielsonsantana** [willbryant/kitchen_sync#103]
I'm trying to use kitchen_sync to sync a managed database at DigitalOcean to a local database.
The problem is that DigitalOcean require `sslmode=require` to connect to database. 
There any way to kitchen_sync support ssl connection?

**Comment by willbryant** [comment]
Are you talking about postgresql? Docs say it should be automatic if you have set up the certs correctly:

> If the server attempts to verify the identity of the client by requesting the client's leaf certificate, libpq will send the certificates stored in file ~/.postgresql/postgresql.crt in the user's home directory. The certificates must chain to the root certificate trusted by the server. A matching private key file ~/.postgresql/postgresql.key must also be present. The private key file must not allow any access to world or group; achieve this by the command chmod 0600 ~/.postgresql/postgresql.key. On Microsoft Windows these files are named %APPDATA%\postgresql\postgresql.crt and %APPDATA%\postgresql\postgresql.key, and there is no special permissions check since the directory is presumed secure. The location of the certificate and key files can be overridden by the connection parameters sslcert and sslkey or the environment variables PGSSLCERT and PGSSLKEY.

**Comment by nielsonsantana** [comment]
Yes, about postgresql. Thanks for your help. I was able to use kitchen_sync without ssl certificates, however it's nice know that is possible.
