### ISSUE TITLE
No homebrew for version 2.6

### ISSUE THREAD

**Issue by heftycrayfish** [willbryant/kitchen_sync#104]
The homebrew bottle specification has changed. I used to install kitchen-sync 2.6 using [an older version of the formula](https://raw.githubusercontent.com/Homebrew/homebrew-core/05af977af32f8cd2abec8347626b2d680cb6a4de/Formula/kitchen-sync.rb) but this isn't compatible with newer versions of homebrew.
Any chance of adding homebrew support for older versions?

**Comment by willbryant** [comment]
I don’t know sorry, I didn’t write the homebrew formula so I don’t really know much about it. They do accept pull requests though - I’ve done one to fix some dependencies.

Why would you want to run an older version? It’s fully backwards compatible back to v1.

**Comment by heftycrayfish** [comment]
I considered opening an MR for a 2.6 version but I don't think we'd have enough users to make it worthwhile. The latest version works as expected for me so I'll only worry about it if that's not the case after an upgrade, which doesn't sounds likely ;). Thanks!
