### ISSUE TITLE
YAML FORMAT

### ISSUE THREAD

**Issue by fendys01** [willbryant/kitchen_sync#107]
hi Willl Bryant I'm using kitchen sync and I'm having a problem using the YAML format.
can you help in any example in yaml format needed in kitchen sync. Because I want to sync data from mysql to postgree

**Comment by willbryant** [comment]
Hi,

The YAML format is only used for filtering the tables. If you just want to sync data from mysql to postgresql, you don't need it.

What are you trying to do?

**Comment by fabioespinosa** [comment]
for filtering yaml format see: https://github.com/willbryant/kitchen_sync/blob/master/FILTERING.md
