### ISSUE TITLE
About release 2.17

### ISSUE THREAD

**Issue by chenrui333** [willbryant/kitchen_sync#112]
👋 it looks like the release 2.17 was not completed? (at least the release did not get marked as the latest release, it does impede this [homebrew version bump PR](https://github.com/Homebrew/homebrew-core/pull/121235)). Create this issue to raise some awareness. Thanks!

**Comment by willbryant** [comment]
My mistake, thanks for raising! Is it OK now?

**Comment by chenrui333** [comment]
yeah, good now. Thanks for fixing the tag issue!
