### ISSUE TITLE
Many idle workers when there is remaining work

### ISSUE THREAD

**Issue by richardmcmillen** [willbryant/kitchen_sync#116]
We are witnessing behaviour that we're not sure is expected. We are using v2.17, _from_ and _to_ MariaDB (12 workers). During the sync of a large database we've seen kitchen_sync eventually end up with many idle workers.

When looking in the destination DB with `show processlist`, 11 out of the 12 connections are in Sleep (ever increasing time in this state) with only one connection actively running statements. It is running `REPLACE INTO` statements and we can see it making progress by viewing the full statement and witnessing that it is slowly getting through the full table in batches (one every couple of seconds)

Here is the [verbose output from kitchen sync](https://gist.github.com/richardmcmillen/1406e2f5a776d10fbef250e844d8a94d) (where I grep'ed only the lines for the remaining table being worked on), "tbl_name" is the large table mentioned, you may see other references to `tbl_name_(a|b|c|d)` as it appears kitichen sync interleaved output from different workers into the same line.

At this point the kitchen sync process is still actually running, but there is no more output printed even though we can see one worker happily running `REPLACE INTO` statements into the destination DB.

Is it expected for the remaining workers to be idle and not coordinate on this large table? And for output to cease even when kitchen sync appears to be continuing to work and using `--verbose`?

The schema for the table in question is

```
+------------------------+---------------+------+-----+---------+----------------+
| Field                  | Type          | Null | Key | Default | Extra          |
+------------------------+---------------+------+-----+---------+----------------+
| id                     | int(11)       | NO   | PRI | NULL    | auto_increment |
| col1                   | int(11)       | YES  | MUL | NULL    |                |
| col2                   | decimal(24,4) | NO   |     | NULL    |                |
| col3                   | datetime      | NO   |     | NULL    |                |
| col4                   | varchar(255)  | NO   |     | NULL    |                |
| col5                   | text          | YES  |     | NULL    |                |
| col6                   | datetime      | YES  |     | NULL    |                |
| col7                   | text          | YES  |     | NULL    |                |
| col8                   | int(11)       | YES  |     | NULL    |                |
| col9                   | varchar(255)  | YES  | MUL | NULL    |                |
| col10                  | datetime      | NO   |     | NULL    |                |
| col11                  | datetime      | YES  | MUL | NULL    |                |
| col12                  | varchar(255)  | NO   |     | NULL    |                |
| col13                  | tinyint(1)    | YES  |     | NULL    |                |
| col14                  | varchar(255)  | YES  |     | NULL    |                |
| col15                  | varchar(255)  | YES  |     | NULL    |                |
| col16                  | varchar(255)  | YES  |     | NULL    |                |
| col17                  | varchar(255)  | YES  |     | NULL    |                |
+------------------------+---------------+------+-----+---------+----------------+
```

**Comment by willbryant** [comment]
There's a lot of situations where we can't parallelize, particularly the writes. Does the table have any unique keys?

**Comment by richardmcmillen** [comment]
Some more detail about this scenario is that this was the one of the first few attempts to sync an empty database, kitchen sync had been run before against this DB, but not to completion, so the large table we see kitchen sync working against may only have been about 5% or less of what the source table contains. Table size is ~316 million rows.

I think I had a misunderstanding about what kitchen sync can parallelise and I've been trying to grasp the contents of https://github.com/willbryant/kitchen_sync/blob/main/src/sync_to_algorithm.h

In particular this part stands out: https://github.com/willbryant/kitchen_sync/blob/main/src/sync_to_algorithm.h#L251 but I must admit I don't don't fully follow what process is doing what and when, and are could be off the mark.

The create table statement is:

```sql
CREATE TABLE `tbl_name` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `col1` int(11) DEFAULT NULL,
  `col2` decimal(24,4) NOT NULL,
  `col3` datetime NOT NULL,
  `col4` varchar(255) NOT NULL,
  `col5` text DEFAULT NULL,
  `col6` datetime DEFAULT NULL,
  `col7` text DEFAULT NULL,
  `col8` int(11) DEFAULT NULL,
  `col9` varchar(255) DEFAULT NULL,
  `col10` datetime NOT NULL,
  `col11` datetime DEFAULT NULL,
  `col12` varchar(255) NOT NULL,
  `col13` tinyint(1) DEFAULT NULL,
  `col14` varchar(255) DEFAULT NULL,
  `col15` varchar(255) DEFAULT NULL,
  `col16` varchar(255) DEFAULT NULL,
  `col17` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_a` (`col1`,`col6`,`col3`),
  KEY `index_b` (`col1`,`col6`,`col4`,`col3`),
  KEY `index_c` (`source`),
  KEY `index_d` (`col1`,`col6`,`col12`,`col3`),
  KEY `index_e` (`col11`)
) ENGINE=InnoDB AUTO_INCREMENT=316632294 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
```

My assumption was that kitchen sync could coordinate working on large tables, and this could happen even when the destination table is nearly empty (only the first N% of rows ordered by primary key exist in destination), and that this would look like multiple workers inserting their designated chunks of rows.

However, looking at the code I see mention of only one writer per table (is that right?) and so we can only ever expect one worker to be mutating the destination table. And for tables where the destination table last key is < source last key, this will result in one worker chugging away making up the difference until the destination is up to date. If this is correct you can close this issue as a misunderstanding about how kitchen sync works. Being able to parallelise syncing large deltas between last keys in source and destinations would certainly be nice but understand that isn't the primary use for KS.

**Comment by willbryant** [comment]
Sorry, had to find time to check myself. Yes, that's right. In the general case it's only possible for one writer because locks on unique indexes and so on may conflict between different rows (the unique values won't conflict when all data is updated, but they may while working on getting there), which is risky as it could result in the threads blocking indefinitely or even (in the case of postgresql) getting errors that cause the transaction to roll back (whether you want it to or not).

That said, there are common "special cases" where it would work just fine. I think I actually had/have a branch that lets multiple threads write in certain scenarios, but when I lost access to high-end hardware I basically stopped working on that kind of thing. Most RDS instances, for example, are heavily bottlenecked on IO, so adding more writer threads isn't necessarily going to help. But it would be interesting to see if that is normally the case for most people right now, especially considering that a lot of CPU is spent writing and parsing SQL etc.
