### ISSUE TITLE
Missing v2.18 from github releases

### ISSUE THREAD

**Issue by flux-ricky** [willbryant/kitchen_sync#118]
I can see from the CHANGES.md that there is a v2.18 and it is what homebrew has installed for me but there isn't an entry in the github releases page: https://github.com/willbryant/kitchen_sync/releases

Is this intentional, it is ok to be used? Or does some process need to be run to get it to turn up there?

**Comment by willbryant** [comment]
Oh oops, I always forget that I have to manually make those in the Github UI, unlike all the publishing platforms like Rubygems and Pub.dev etc. :(

Yes, definitely fine to use.

The most annoying thing is I can't backdate the release on Github!
