### ISSUE TITLE
cipher blowfish not supported

### ISSUE THREAD

**Issue by aclemons** [willbryant/kitchen_sync#14]
Running kitchen_sync on Slackware fails since the blowfish cipher is not supported. I am currently patching before building to work around this, but maybe we can make it configurable at runtime or have the makefile detect this?

```sh
aclemons@host ~ $ ssh -Q cipher
3des-cbc
blowfish-cbc
cast128-cbc
arcfour
arcfour128
arcfour256
aes128-cbc
aes192-cbc
aes256-cbc
rijndael-cbc@lysator.liu.se
aes128-ctr
aes192-ctr
aes256-ctr
aes128-gcm@openssh.com
aes256-gcm@openssh.com
chacha20-poly1305@openssh.com
aclemons@host ~ $ ssh -V
OpenSSH_7.2p2, OpenSSL 1.0.2h  3 May 2016
```

**Comment by willbryant** [comment]
Yeah, an option is probably the best solution.  Want to make a PR?

**Comment by denji** [comment]
__~$USER/.ssh/config__
```
Host *
    Ciphers …
    HostKeyAlgorithms …
    KexAlgorithms …
    MACs …
    Protocol 2 …
```

**Comment by denji** [comment]
https://github.com/willbryant/kitchen_sync/blob/0f8ba82847fe132c66a6f5a11f24629d376d5414/src/ks.cpp#L49

**Comment by aclemons** [comment]
@denji Yes simplest would be to remove the -c option in ks.cpp (what I did in my patch) and have the user configure the preferred cipher in the user's ssh config. This would change the default behaviour for users when upgrading though. 

[This](https://github.com/willbryant/kitchen_sync/commit/30371b262505e5cf6e356776539de89d85818780) says @willbryant added it to increase the encryption speed.

**Comment by willbryant** [comment]
I think arcfour was a close competitor out of the set that were considered "still good enough to use", I can't remember the numbers though.  Do you know why blowfish is not supported?

**Comment by denji** [comment]
https://pthree.org/2015/01/12/reasonable-ssh-security-for-openssh-6-0-or-later/

**Comment by willbryant** [comment]
Thanks, that is useful.  Based on that I think arcfour would be a reasonable default for the Kitchen Sync use cases I know of, since performance is very much an issue.  How about we change that for now and hope someone makes a PR to add a KS option to select the SSH cipher?

**Comment by normanv** [comment]
Following this discussion I have summited a PR if you would like to review it. I set arcfour as the default cipher as you discussed but note that arcfour is disabled by default in OpenSSH 7.2 just like blowfish.

**Comment by willbryant** [comment]
Oh, that sucks.  Is there another "fast" cipher in 7.2?

**Comment by denji** [comment]
@willbryant `HPN-SSH` + `NONE Cipher`
* https://www.psc.edu/index.php/hpn-ssh
* https://sourceforge.net/projects/hpnssh/
* https://github.com/rapier1/openssh-portable

**Comment by willbryant** [comment]
So if we want to use standard openssh builds, none of these options will work?  What is the next best cipher for speed that will still work in 7.2, without turning of encryption entirely?  NONE seems a step too far.

**Comment by normanv** [comment]
Here is the list of available ciphers with OpenSSH 7.2 : chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com

Here is an interesting benchmark of ssh ciphers :
https://blog.famzah.net/2015/06/26/openssh-ciphers-performance-benchmark-update-2015/

This post is a bit more than a year old and suggest that AES speed would be faster than arcfour or blowfish with new CPU generation (and few of them) that benefits from AES hardware acceleration. 

So we just need to choose between AES-CTR and AES-GCM. CTR seems a bit faster with small resources while GCM seems faster with bigger resources.

**Comment by willbryant** [comment]
Hmm.  We should maybe try this out ourselves (just use SCP to transfer a big file, we don't need to test kitchen sync) - I think I found that blowfish was much faster when I wrote that default, but maybe when I tested it I was using a server that was old generation.

**Comment by normanv** [comment]
Here are the results of speed tests performed on a machine with an Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60GHz having 4 physical cores (8 threads) and AES hardware acceleration. CPU was 100% idle before each test and reach load of ~ 25% during each test.

chacha20-poly1305@openssh.com => 142.9MB/s
aes128-ctr => 181.8 MB/s
aes192-ctr => 181.8MB/s
aes256-ctr => 187.5 MB/s
aes128-gcm@openssh.com => 200.0MB/s
aes256-gcm@openssh.com => 206.9MB/s
blowfish => 85.7MB/s
arcfour => 153.9MB

aes256-gcm@openssh.com seems to be the fastest. Shall I set it as the default cipher?

**Comment by willbryant** [comment]
PR #16 closes this issue.
