### ISSUE TITLE
Couldn't exec ks_postgres: No such file or directory

### ISSUE THREAD

**Issue by jgillman** [willbryant/kitchen_sync#18]
I'm installing for the first time on Ubuntu Trusty.

When I run `ks` I get the error:

```
Couldn't exec ks_postgres: No such file or directory
```

When I ran `make install` I noticed that it installs to `/usr/local/bin/ks_postgresql`. Note the "ql" at the end vs no "ql" in the error.

```
$ which ks_postgresql
/usr/local/bin/ks_postgresql

$ which ks_postgres
ks_postgres not found
```

**Comment by jgillman** [comment]
Output from each step of building: https://gist.github.com/jgillman/fc79a63b4f260a8d82d221c2424ca0d7

**Comment by jgillman** [comment]
Symlinking `ks_postgres` to `ks_postgresql` works, though I'm encountering a different error which I'll explore more and open another issue for 😄

**Comment by willbryant** [comment]
What database URL are you using?

**Comment by denji** [comment]
src/ks.cpp
```cpp
38:    		string from_binary(options.from_path + "ks_" + options.from.protocol);
39:    		string   to_binary(binary_path + "ks_" +   options.to.protocol);

```

```diff
- postgres://someuser:mypassword@localhost/somedb
+ postgresql://someuser:mypassword@localhost/somedb
```

**Comment by jgillman** [comment]
Huh! You are 100% correct. I copy/pasted the url from my Heroku config which appears to use `postgres://`. Thanks!

**Comment by willbryant** [comment]
Aha.  This seems like a bit of a trap for new players to fall into.  I wouldn't mind a PR to change the "postgres" to "postgresql"...

**Comment by jgillman** [comment]
@willbryant I have no experience with C++, but maybe a "gotchas" section of the README or USAGE would suffice?
