### ISSUE TITLE
Support loading of table records from bottom to top

### ISSUE THREAD

**Issue by dylanmckay** [willbryant/kitchen_sync#22]
It would be useful if kitchen sync could start with the records at the bottom of the tables, so that only the most recent records were fetched.

**Comment by willbryant** [comment]
I don't think I follow.  Why would only the most recent records be fetched if we started at the bottom?

**Comment by dylanmckay** [comment]
The most recent records would be fetched first. If this were implemented, it would be trivial to stop after `n` records, which would be one way to ignore old records to reduce sync time.

Probably not that useful, but it's worth mentioning
