### ISSUE TITLE
escaped character for password in connection string

### ISSUE THREAD

**Issue by Leidanya** [willbryant/kitchen_sync#23]
the program currently doesn't accept characters such as @ in password connection string even with proper bash ecapes.

https://github.com/willbryant/kitchen_sync/blob/master/src/db_url.cpp#L78

**Comment by willbryant** [comment]
It should.  Did you URL encode them correctly?

**Comment by willbryant** [comment]
No further info, so I assume that this is just a case of not encoding the characters as required.
