### ISSUE TITLE
How I can customize MySQL client unix socket parameter?

### ISSUE THREAD

**Issue by vafrcor** [willbryant/kitchen_sync#28]
I have an issue, kitchen sync result with failed response:
```
Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Connection closed
Connection closed
Connection closed
Connection closed
Kitchen Syncing failed.
```
Any help how to customize `unix_socket` path?

**Comment by denji** [comment]
my.cnf
-------
    ; server
    [mysqld]
    socket=/var/run/mysqld/mysqld.sock
    ; cli
    [client]
    socket=/var/run/mysqld/mysqld.sock

**Comment by willbryant** [comment]
As @denji says.  The default socket path is compiled into your libmysqlclient library.  Usually this will match the server if you have installed client and server from the same source.  If not, you can override as suggested above.
