### ISSUE TITLE
Custom Types transformation rules . 

### ISSUE THREAD

**Issue by neshwill** [willbryant/kitchen_sync#29]
Can you explain how to write custom types trasformation rules , in case we sync db from mysql to postgresql database . 

i suppose it should be some .yml file , but can you give  example how to write it ? 

Thank you in advance , 

Konstantin

**Comment by willbryant** [comment]
Unfortunately we don't have such a customisation feature, but that is a good idea we should consider for the future.

Instead I have been trying to add explicit mappings for types as people request them.

Which mysql type is missing for you at the moment?

**Comment by willbryant** [comment]
Needs more info.  Please reopen if you can provide them.
