### ISSUE TITLE
SSH with non standard port

### ISSUE THREAD

**Issue by ernovout** [willbryant/kitchen_sync#30]
I'm trying to run `ks --via myserver.loc:2233 ...` since my source server has ssh running on port 2233.  As a result I'm getting:
```
ssh: Could not resolve hostname myserver.loc:2233: nodename nor servname provided, or not known
Error in the 'to' worker: Connection closed
Kitchen Syncing failed.
```

Am I doing something wrong or is it not possible to set the ssh port manually?

**Comment by denji** [comment]
~/.ssh/config
=========

```yaml
#Host subnetwork-host
# ...
Host MyHost
    # ProxyJump subnetwork-host # man ssh_config
    HostName myserver.loc
    User root
    Port 2233
```

**Comment by willbryant** [comment]
@ernovout That error came from SSH, not KS.  I don't think it's a KS issue, probably myserver.loc does not resolve.

@denji's suggestion should work :).

**Comment by ernovout** [comment]
Great! Thanks! It does work 👍
