### ISSUE TITLE
--ignore fails on unsupported schema (enum)

### ISSUE THREAD

**Issue by ernovout** [willbryant/kitchen_sync#31]
I'm trying to run ks on a MySQL database with a table containing an **enum** field. Enum doesn't seem to be supported at the moment, so I tried to --ignore the table but with no luck:
```
Error in the 'from' worker: Don't know how to represent mysql type of mytable.mycolumn (enum('val1','val2','val3'))
```
Either having support for enum columns or letting the --ignore skip the schema check for ignored tables would solve this issue.

**Comment by willbryant** [comment]
This shouldn't be too hard to fix. Any chance you could submit a test case for an unsupported type?

**Comment by ernovout** [comment]
That's good to hear 🙂 Sure thing I can. Here's a table and some data you can test this with (I've sent these to your email in a zipped dumpfile aswell):
```sql
CREATE TABLE `mytable` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mycolumn` enum('val1','val2','val3') CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

INSERT INTO `mytable` VALUES (1,'val1'),(2,'val2'),(3,'val3');
```
