### ISSUE TITLE
Issue "Don't know how to interpret type of column"

### ISSUE THREAD

**Issue by nusken** [willbryant/kitchen_sync#54]
Hi @willbryant 

I'm using ks to sync some tables between 2 postgres databases. Here is the command I use:

`ks --from postgresql://havs:123@localhost/welligence_development --to postgresql://havs:123@localhost/welligence_brazil --only countries`

Here is the error message I got: **Don't know how to interpret type of countries.name (character varying)**

According to the [supported schema](https://github.com/willbryant/kitchen_sync/blob/master/SCHEMA.md), I understand that the column with type **character varying** should be supported and I should not encounter this issue. Any idea?

**Comment by willbryant** [comment]
That is weird.  Looks like it's something to do with not having a length suffix, as in `character varying(100)`.  I didn't know you could leave that off!

**Comment by nusken** [comment]
@willbryant 

Thank you for you response.

Did you mean I cannot use `ks` for a table which have a character varying column without declaring length. I usually add a string column without length and I do know lots of people also do that. Do you have a plan to have a release to support this data type (`character varying` without length)?

**Comment by nusken** [comment]
@willbryant 

I have tried alter the table to add `length` to `character varying` column. But I encounterd another issue:

`Error in the 'to' worker: ERROR:  update or delete on table "countries" violates foreign key constraint "fk_rails_1630089669" on table "facilities"`

According to this error message I understand that `ks` cannot sync a table which have PK is a FK of other tables, right?

**Comment by willbryant** [comment]
I've found this in the postgresql docs: 

> If `character varying` is used without length specifier, the type accepts strings of any size. The latter is a PostgreSQL extension.

I just didn't know about that extension.  I'll see if I can add support in the next version.

**Comment by willbryant** [comment]
I'm a bit surprised about the other issue because KS does a `SET CONSTRAINTS ALL DEFERRED`.  Could you please open a separate issue for that and attach a log using `--debug` mode?

**Comment by willbryant** [comment]
Oh, the other issue is probably because you are using `--only countries`. Try again without that and open another issue if the problem persists?
