### ISSUE TITLE
Issue: violates foreign key constraint

### ISSUE THREAD

**Issue by nusken** [willbryant/kitchen_sync#55]
@willbryant 

As your request in #54, I create this new issue. Here is my command:

`ks --from postgresql://havs:123@localhost/welligence_development --to postgresql://havs:123@localhost/welligence_brazil --only countries --debug`

Here is the debug log

> Kitchen Sync
> from command: ks_postgresql from localhost - welligence_development havs 123 -
> 1551881536.810149 worker 0 starting countries
> 1551881536.810212 worker 0 <- range countries
> 1551881536.810747 -> range countries (1) (18)
> 1551881536.811430 worker 0 <- hash countries (NULL) (9) 1
> 1551881536.811804 worker 0 -> hash countries (NULL) (9) 1 doesn't match
> 1551881536.811822 worker 0         countries has 3 range(s) to check and 1 to retrieve, sharing not needed
> 1551881536.811829 worker 0 <- rows countries (NULL) (1)
> 1551881536.811839 worker 0 <- hash countries (1) (5) 221
> 1551881536.812029 worker 0 -> rows countries (NULL) (1)
> 1551881536.812216 worker 0 <- hash countries (5) (9) 221
> 1551881536.812404 worker 0 -> hash countries (1) (5) 4 doesn't match
> 1551881536.812417 worker 0         countries has 1 range(s) to check and 1 to retrieve, sharing not needed
> 1551881536.812427 worker 0 <- rows countries (1) (5)
> 1551881536.812441 worker 0 -> hash countries (5) (9) 4 doesn't match
> 1551881536.812449 worker 0         countries has 1 range(s) to check and 1 to retrieve, sharing not needed
> 1551881536.812458 worker 0 <- rows countries (5) (9)
> 1551881536.812620 worker 0 -> rows countries (1) (5)
> 1551881536.812837 worker 0 <- hash countries (9) (18) 1
> 1551881536.813173 worker 0 -> rows countries (5) (9)
> 1551881536.813362 worker 0 -> hash countries (9) (18) 1 doesn't match
> 1551881536.813376 worker 0         countries has 2 range(s) to check and 1 to retrieve, sharing not needed
> 1551881536.813386 worker 0 <- rows countries (9) (10)
> 1551881536.813401 worker 0 <- hash countries (10) (14) 184
> 1551881536.813624 worker 0 -> rows countries (9) (10)
> 1551881536.813824 worker 0 <- hash countries (14) (18) 184
> 1551881536.814024 worker 0 -> hash countries (10) (14) 4 doesn't match
> 1551881536.814037 worker 0         countries has 0 range(s) to check and 1 to retrieve, sharing not needed
> 1551881536.814045 worker 0 <- rows countries (10) (14)
> 1551881536.814057 worker 0 -> hash countries (14) (18) 4 doesn't match
> 1551881536.814063 worker 0         countries has 0 range(s) to check and 1 to retrieve, sharing not needed
> 1551881536.814071 worker 0 <- rows countries (14) (18)
> 1551881536.814236 worker 0 -> rows countries (10) (14)
> 1551881536.814450 worker 0 -> rows countries (14) (18)
> Error in the 'to' worker: ERROR:  update or delete on table "countries" violates foreign key constraint "fk_rails_1630089669" on table "facilities"
> DETAIL:  Key (id)=(4) is still referenced from table "facilities".
> 
> DELETE FROM countries WHERE (id=1)
> OR (id=2)
> OR (id=3)
> OR (id=4)
> OR (id=5)
> OR (id=6)
> OR (id=7)
> OR (id=8)
> OR (id=9)
> OR (id=10)
> OR (id=11)
> OR (id=12)
> OR (id=13)
> OR (id=14)
> OR (id=15)
> OR (id=16)
> OR (id=1...
> Error in the 'from' worker: Connection closed
> Kitchen Syncing failed.

**Comment by willbryant** [comment]
Hmm.  There might be multiple problems here.  The first one is that you're using `--only countries`, so the `facilities` table rows that depend on `countries` are not getting cleared.  What happens if you try again without that option?

**Comment by nusken** [comment]
@willbryant 

I don't want to (and cannot) sync `facilities` table so remove `--only countries` should not be a solution for me. My app connects to multiple databases. A master database which is used to store global data and `country-based database` to store specified data for each country. Only table `countries` and some others should be synced from the master database to `country-based database`. If the table `facilities` is also synced, it will be a big problem for my app.

**Comment by willbryant** [comment]
Then you need to make sure that all the `countries` rows that are going to be deleted are not depended on by the `facilities` rows that exist in the destination database, don't you?

**Comment by willbryant** [comment]
This seems like a schema problem not a bug.  KS can't delete rows that violate your foreign key constraints.
