### ISSUE TITLE
kitchen_sync parses tinyint(2) as boolean

### ISSUE THREAD

**Issue by alfredballe** [willbryant/kitchen_sync#56]
I have the following source MariaDB database:

CREATE TABLE 'test' (
  'id' int(10) NOT NULL AUTO_INCREMENT,
  'time' tinyint(2) DEFAULT '20'
);

with the following record in it:

SELECT * FROM test;
id | time
1 | 20

When running ks I get the following error:

1553852889.477541 worker 0 starting test
1553852889.477762 worker 0 <- range test
1553852889.545032 -> range test (1) (1)
1553852889.645944 worker 0 <- rows test (NULL) (1)
1553852889.679986 worker 0 -> rows test (NULL) (1)
Error in the 'to' worker: ERROR:  column "time" is of type smallint but expression is of type boolean
LINE 2: ...1,false...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

INSERT INTO test VALUES
(1,false...
Error in the 'from' worker: Connection closed
Kitchen Syncing failed.

**Comment by willbryant** [comment]
That's weird.  It's only meant to do that for `tinyint(1)` and only if the default value is `0`, `1`, or `NULL`.  I'll look into it.

**Comment by willbryant** [comment]
Yeah, https://github.com/willbryant/kitchen_sync/blob/62bec11f05c56d7024a9629d685f2c6b74b098fe/src/ks_mysql.cpp#L74 needs to have the same checks as https://github.com/willbryant/kitchen_sync/blob/62bec11f05c56d7024a9629d685f2c6b74b098fe/src/ks_mysql.cpp#L538.  Will have to parse some more field metadata to determine the correct conversion, should be doable.

Of course, anyone using `tinyint(1)` to store actual numbers is still going to have a bad time, but not much we can do about that unless/until we make the mappings customisable.

**Comment by willbryant** [comment]
Ugh, MySQL API docs say `MYSQL_FIELD->def` is not set for resultsets, only by `mysql_list_fields`.  That means the correct encoding can't be determined from inspecting the resultset, which the code currently needs to do.  Gonna have to have a think about how to workaround this.

**Comment by willbryant** [comment]
Fixed in the next release.
