### ISSUE TITLE
Running ks in the background keeping databases in sync

### ISSUE THREAD

**Issue by alfredballe** [willbryant/kitchen_sync#57]
Is it possible to run ks in the background keeping databases in sync (near) realtime?

**Comment by willbryant** [comment]
You can run it as often as you like, but it doesn't have anything built-in.  It doesn't implement interpretation of binlogs, so it would have to rescan the whole database each time.  For large databases, this would probably not be very good use of resources :).

You might like Tungsten if you want continuous replication?
