### ISSUE TITLE
Unique Key required

### ISSUE THREAD

**Issue by MaxRichter** [willbryant/kitchen_sync#58]
Hi,

I was using the KS (v. 1.13) to sync from Postgres to MySQL and got the following output:

```
Kitchen Sync
Couldn't find a primary or non-nullable unique key on table spinstrumentsector
Kitchen Syncing failed.
```

Is there any possibility I can still make the sync work?

**Comment by willbryant** [comment]
I'm sorry but no, I haven't implemented support for tables with no primary key or suitable unique key.  It could be done in theory.  Could you tell me more about your schema?

In particular, do you really want to allow rows that are complete duplicates?

**Comment by willbryant** [comment]
Also, are any of your columns nullable in that table?

**Comment by willbryant** [comment]
I have a branch that might solve this, but need the questions above answered to confirm.

**Comment by MaxRichter** [comment]
Hi Will,
sorry for the late response - I would have preferred a primary key, but unfortunately I can not change the table format as I get this delivered.

The table has 5 columns, where of the first 3 are not null-able, the last 2 are.
The first 3 columns produce as I see it a unique key - the last two are more or less unimportant.

I hope this helps, otherwise I can also attach an example.

**Comment by willbryant** [comment]
Hmm yeah, that's a tough case.  The fact that there's no primary or unique key and there are nullable columns means there's no way to query for ranges of the table, which makes it very hard to sync.

Is this the only table you want to sync, or is it one table in a bigger database?

**Comment by MaxRichter** [comment]
I agree, I already contacted the support mentioning the case - but it does not look like they are changing it soon or even at all.

There are two table affected by this of of around 50 from a whole database.

**Comment by willbryant** [comment]
Yeah, I wonder how they access the table.  Technically the current release of KS doesn't require a primary key, just any unique key that's non-nullable, but you have to have some way to refer to the specific row(s).

If it's only 2 out of 50 then potentially there would be some value in letting KS just do a full 'dumb' reload of those two tables and still use its normal efficient syncing algorithm on the rest of the tables.  How big are those two tables compared to the rest of the database?

Also, is there an index covering the 3 non-null-able columns?

**Comment by MaxRichter** [comment]
Hey, 
the tables are comparably small, they both have around 16 MB.
There is an index, on the first 4 columns. So one of the nullables is in the index, one out.

**Comment by willbryant** [comment]
OK interesting.  I've started experimenting with whether it would be possible to use the non-nullable parts of the index as a pseudo-key and allow multiple rows, but it's not easy so might take a while to get right.

If you would like to go ahead with testing out kitchen sync in the meantime, you can try compiling the origin/no_pk branch. The last commit on that branch will make it clear and reload these tables that aren't supported by the proper syncing algorithm, so at least it can go ahead with syncing the rest of the database the normal more-efficient way.

**Comment by willbryant** [comment]
OK, I have finished a draft implementation of full syncing using the normal algorithm for even tables with no primary key or substitute!  It's pushed to master in origin/partial_key.

@MaxRichter for the table you mentioned, it should find that key that's almost-unique, and use that like a pseudo-primary-key but allow multiple rows and duplicates.

Could you please try it?  I don't have any real world data to test the algorithm with because I always have PKs on my table.

**Comment by MaxRichter** [comment]
Hi Will,

thank you for the effort - I will test it starting tomorrow and give you feedback!

**Comment by MaxRichter** [comment]
Hi Will,

the problem with the keys is solved with the branch!

Now I am experiencing the following behavior, that the process seems to be stuck when syncing. This happened when syncing a table of size 2.8 GB, it just hang in a loop.

Any idea what can cause this behavior?
What is the batch size of the data you are sending?

**Comment by willbryant** [comment]
OK, that's good progress.  I've probably introduced a bug on this branch - I had to change some intricate bits of code.  Is the table that it gets stuck on one of the ones with no primary key?

When you say stuck, do you mean it's stuck on 100% CPU, or frozen on 0% CPU? Do you see a loop in the commands when you run it with `--debug`?

The batch size is dynamic - it increases the batch size when the data mostly matches and decreases it when it mostly doesn't match.  We've used KS on tables that are hundreds of gigabytes.

**Comment by MaxRichter** [comment]
Hi Will,

I retried it with more parallel connections (4) and it worked like a charm.
Yes before with just one worker it took ages, so it was actually not frozen.

Thank you a lot, my use-case is now covered with the branch!
When will the branch be merged into the master?

**Comment by willbryant** [comment]
Great!  In principle it can be merged and released straight away but I feel like it probably needs a bit more testing, so just need to figure out how to do that.

Were you able to compare the results after the sync to see if the data matched?

**Comment by willbryant** [comment]
I've been doing some testing on this one.  I was surprised how poorly it performs, with both mysql & postgresql burning a LOT of CPU.

It turns out that for my sample tables, even if there is an index providing nearly-unique row ids, including the other columns in the ORDER BY causes both of them to change query plans and not use the index.  They do different things, but both of them are terrible.

This is very unfortunate.  I can't easily not include those extra columns because if the rows come back in different orders the hashes won't match, and I'm very reluctant to do an extra sort outside the database.

Will think some more on it.

For future reference, here's the script I'm using at the moment to test.

```ruby
#!/usr/bin/env ruby
# require 'pg'
require 'mysql2'

puts "seed #{Process.pid}"
srand Process.pid

row_count = 1000000
workers = 1

# @connections = [
#   PG.connect("localhost", "5432", nil, nil, "mut1", "will", ""),
#   PG.connect("localhost", "5432", nil, nil, "mut2", "will", ""),
# ]

@connections = [
  Mysql2::Client.new(host: "localhost", port: "3306", database: "mut1", username: "root"),
  Mysql2::Client.new(host: "localhost", port: "3306", database: "mut2", username: "root"),
]

def each_connection
  @connections.each { |connection| yield connection }
end

def most_connections
  @connections.each { |connection| yield connection if rand(100) < 99 }
end

def random_connection
  @connections.sample
end

@connections.each { |connection| connection.query "DROP TABLE IF EXISTS muttbl" }
@connections.each { |connection| connection.query "CREATE TABLE muttbl (id integer not null, payload1 integer not null, payload2 integer)" }
@connections.each { |connection| connection.query "CREATE INDEX mutidx ON muttbl (id, payload1)" }

@connections.each { |connection| connection.query "BEGIN" }

(row_count + rand(100)).times do |id|
  v1 = rand(2**31)
  v2 = rand(10).zero? ? "NULL" : rand(2**31)
  most_connections { |connection| connection.query "INSERT INTO muttbl (id, payload1, payload2) VALUES (#{id}, #{v1}, #{v2})" }
  # most_connections { |connection| connection.query "INSERT INTO muttbl (id, payload1, payload2) VALUES (#{id}, #{v1}, #{v2})" } if rand(20).zero?
  # most_connections { |connection| connection.query "INSERT INTO muttbl (id, payload1, payload2) VALUES (#{id}, #{v1}, #{rand(2**31)})" } if rand(20).zero?
  # most_connections { |connection| connection.query "INSERT INTO muttbl (id, payload1, payload2) VALUES (#{id}, #{v1 + 1}, #{v2})" } if rand(10).zero?
end

# rand(100).times do |i|
#   start = rand(row_count)
#   random_connection.query "DELETE FROM muttbl WHERE id BETWEEN #{start} AND #{start + rand(100)}"
# end

# rand(100).times do |i|
#   start = rand(row_count)
#   random_connection.query "UPDATE muttbl SET payload1 = payload1 + 1 WHERE id BETWEEN #{start} AND #{start + rand(100)}"
# end

@connections.each { |connection| connection.query "COMMIT" }

puts "syncing"
Process.wait spawn("build/ks --from postgresql://will@localhost/mut1 --to postgresql://will@localhost/mut2 --debug --workers #{workers} >mut-out.txt")
Process.wait spawn("build/ks --from postgresql://will@localhost/mut1 --to postgresql://will@localhost/mut2 --verbose")
```

**Comment by willbryant** [comment]
Tagged those commits with the wrong issue number, this one isn't merged yet, due to the above issue with performance.

**Comment by willbryant** [comment]
Since I haven't worked around the query performance issue yet, I've instead committed:

* c0e9b4c Support for tables with no primary key and no usable unique key but that do have a key and all columns non-nullable.
* fa170f5 Simply clear and reload tables that have no primary key and no suitable substitute, rather than erroring out.

Which isn't as efficient as the "partial key" approach in the branch I was working on here, but which does at least cover the basic use case where there are a smaller number of tables that can't be synced efficiently and a larger number that can.
