### ISSUE TITLE
PostgreSQL: arrays don't seem to be supported

### ISSUE THREAD

**Issue by frysztak** [willbryant/kitchen_sync#60]
When trying to synchronise two Postgre DBs, I get the following message:
```
Kitchen Sync
Don't know how to interpret type of movie.genres (text[])
Kitchen Syncing failed.
```

Column `genres` in table `movie` is indeed of array type. Is it currently supported?

**Comment by willbryant** [comment]
Unfortunately no, per https://github.com/willbryant/kitchen_sync/blob/master/SCHEMA.md.

At the moment only types portable across databases are supported.  There's two possible ways forward - either someone thinks of a logical thing to convert arrays to on other databases, or we add support for syncing non-portable types as long as you're using the same database at both ends.
