### ISSUE TITLE
Don't know how to interpret type of ... (numeric)

### ISSUE THREAD

**Issue by tomSDL** [willbryant/kitchen_sync#65]
ks --from postgresql://logsreader_single:password@192.168.99.1/database_single --to mysql://username:password@localhost/3CX --debug

Kitchen Sync
from command: ks_postgresql from 192.168.99.1 - database_single logsreader_single  -
Don't know how to interpret type of cl_participants.billing_rate (numeric).  Please check https://github.com/willbryant/kitchen_sync/blob/master/SCHEMA.md.
Kitchen Syncing failed.

**Comment by willbryant** [comment]
Hmm, `numeric(n)` and `numeric(n, m)` are supported, but it looks like postgresql lets you use `numeric` with no length choice and use arbitrary implementation-defined precision, which is not what the SQL standard says to do - according to the postgresql manual:

> The SQL standard requires a default scale of 0, i.e., coercion to integer precision. We find this a bit useless. If you're concerned about portability, always specify the precision and scale explicitly.

I'll try and figure out how to handle this.  I guess I need to find out what the actual implementation type uses.

**Comment by willbryant** [comment]
Fix released in v1.17.
