### ISSUE TITLE
ks_postgresql not found

### ISSUE THREAD

**Issue by jakubgarfield** [willbryant/kitchen_sync#7]
Followed the installation steps on Ubuntu 15.04 and ran into the following.

```
Couldn't exec ks_postgresql: No such file or directory
Couldn't exec ks_postgresql: No such file or directory
Finished Kitchen Syncing.
```

Running `PostgreSQL 9.4.4 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2, 64-bit`

Any idea what I might have missed?

**Comment by willbryant** [comment]
Installed from git or from homebrew?

**Comment by jakubgarfield** [comment]
From git according to installing instructions for Ubuntu.

**Comment by willbryant** [comment]
OK.  So I guess the main thing to check is whether it actually compiled it for postgresql - if it couldn't find the headers then it won't have.

So can you post the output of the cmake step?

**Comment by jakubgarfield** [comment]
It didn't compile for Postgre

```
-- Boost version: 1.55.0
-- checking for module 'yaml-cpp'
--   found yaml-cpp, version 0.5.1
-- Could NOT find PostgreSQL (missing:  PostgreSQL_TYPE_INCLUDE_DIR) (found version "9.4.4")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jakub/projects/kitchen_sync/build
```

**Comment by denji** [comment]
@jakubgarfield Check $PATH and /usr/include/postgresql/catalog

```bash
cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
      -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/catalog \
      /home/jakub/projects/kitchen_sync
```

###### CMAKE_INSTALL_PREFIX=/usr/local
* /usr/local/bin/ks_postgresql
* /usr/local/bin/ks_mysql
* /usr/local/bin/ks

###### CMAKE_INSTALL_PREFIX=/usr
* /usr/bin/ks_postgresql
* /usr/bin/ks_mysql
* /usr/bin/ks

**Comment by jakubgarfield** [comment]
Awesome, that worked. Thanks @denji
