### ISSUE TITLE
Recognise/skip generated columns

### ISSUE THREAD

**Issue by willbryant** [willbryant/kitchen_sync#71]
MariaDB 5.2+, MySQL 5.7+, PostgreSQL 12+ all support generated columns.  Currently we will ignore the fact that they are generated and attempt to write to them, which of course won't work.

**Comment by JC1738** [comment]
@willbryant 

I am not sure if this is the same issue, but if you are syncing from Source A to Target B a table named foo:  

If Target B.foo has an extra column that doesn't exist in Source A.foo will that column be ignored?

Thanks,
Jim

**Comment by willbryant** [comment]
No, Kitchen Sync will offer to alter the schema at the receiving end.  It doesn't support syncing with any kind of deliberate schema mismatches at present, with the sole exception that you can ignore entire tables.
