### ISSUE TITLE
Adding non-null boolean columns on postgresql

### ISSUE THREAD

**Issue by easeev** [willbryant/kitchen_sync#75]
I am getting the following error:

```
ALTER TABLE "x" ADD "y" boolean NOT NULL DEFAULT 0
ERROR:  column "y" is of type boolean but default expression is of type integer
HINT:  You will need to rewrite or cast the expression.
```

As per https://en.wikibooks.org/wiki/Converting_MySQL_to_PostgreSQL and http://www.mysqltutorial.org/mysql-boolean/,
>MySQL Booleans are an alias for TINYINT(1); PostgreSQL doesn't auto-convert numbers into booleans.

>MySQL does not have built-in Boolean type. However, it uses TINYINT(1) instead. To make it more convenient, MySQL provides BOOLEAN or BOOL as the synonym of TINYINT(1).

Since BOOLEAN and BOOL are aliases, perhaps it would be easy to support them?

**Comment by willbryant** [comment]
This is already meant to be implemented; see https://github.com/willbryant/kitchen_sync/blob/v1.17/src/ks_mysql.cpp#L574.  Could you please post your schema snippet, command, and versions (database server(s) and KS).

**Comment by willbryant** [comment]
Cancel that, that's unrelated.  This problem will be coming from the code that adds a non-nullable column, which on postgresql has to be done by adding the column with a default value and then taking it away.

https://github.com/willbryant/kitchen_sync/blob/master/src/schema_matcher.h#L235

I fixed a similar problem for adding non-nullable UUID on postgresql in 1f244f979f59337c9852455123bf8df586ca14e3.  Something similar will be required to fix this issue, but as that L235 comment shows, it will be a little trickier.

**Comment by easeev** [comment]
Workarounded by:

```
=> ALTER TABLE "x" ADD "y" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE
```

Then ran Kitchen Sync:

```
Kitchen Sync
ALTER TABLE "x" ALTER "y" DROP DEFAULT
starting x
finished x in 1s using 9 hash commands and 7 rows commands changing 567 rows
Finished Kitchen Syncing.
```
