### ISSUE TITLE
Continuous Sync

### ISSUE THREAD

**Issue by nroose** [willbryant/kitchen_sync#76]
We would like to keep a postgres db up to date with a mysql db. Can you give advice on how? Should we just run the sync periodically? Just run it over and over? Is there documentation? Are people doing this? Thank you!!!

**Comment by willbryant** [comment]
Unfortunately there's nothing special in kitchen sync to help with this particular use case, so yeah you'd just want to run it on a loop or periodically. A loop is safer than using cron in that you don't want to risk overlapping runs.

If you need truly continuous replication, another option worth considering is Confluent's Tungsten Replicator.
