### ISSUE TITLE
Database schema detected as not matching, unsure why

### ISSUE THREAD

**Issue by hsenot** [willbryant/kitchen_sync#78]
Hi there,

We have had issues syncing some (but not all tables) from our PROD (PostgreSQL 11.2 on ubuntu) to our DEV environment (PostgreSQL 11.6 on ubuntu):

`ks --from postgresql://db_user:db_pwd@prod_server:5432/db_name --to postgresql://db_user:db_pwd@localhost:5432/db_name --only meters --verbose --workers 4 --set-from-variables="timezone='Australia/Melbourne'"`

which produces:

```
Kitchen Sync
The database schema doesn't match.  Use the --alter option if you would like to automatically apply the following schema changes:

-- meters: columns match, primary key columns don't match, keys match;
DROP TABLE "meters";
CREATE TABLE "meters" (
  "id" integer NOT NULL,
  "number" character varying(16),
  "icp_id" integer NOT NULL,
  PRIMARY KEY("icp_id", "id"));
CREATE INDEX "app_meter_icp_id_004d0d3c" ON "meters" ("icp_id");

Database schema needs migration.
Kitchen Syncing failed.
```

I checked the schema definitions (managed by Django migrations) but they are identical in both environments:

```
CREATE TABLE public.meters
(
    id integer NOT NULL,
    "number" character varying(16) COLLATE pg_catalog."default",
    icp_id integer NOT NULL,
    CONSTRAINT app_meter_pkey PRIMARY KEY (id),
    CONSTRAINT app_meter_icp_id_004d0d3c_fk_app_icp_id FOREIGN KEY (icp_id)
        REFERENCES public.icps (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX app_meter_icp_id_004d0d3c ON public.meters USING btree (icp_id) TABLESPACE pg_default;
```
Note the PK is on "id" in both DEV and PROD but kitchen_sync suggests to put a primary key on ("icp_id", "id") to align the schemas, which is puzzling.

I've tried both with the 2.0RC1 and 1.17 but couldn't get ks to synchronise all tables (some do, some don't). Is there something I am missing?

Thanks!

**Comment by willbryant** [comment]
I tried that table schema and it worked fine for me.  Does this work for you with otherwise empty databases?:

```
$ createdb h1
$ createdb h2
$ psql h1
psql (11.5)
Type "help" for help.

h1=# create table public.icps (id integer not null primary key);
CREATE TABLE
h1=# CREATE TABLE public.meters
h1-# (
h1(#     id integer NOT NULL,
h1(#     "number" character varying(16) COLLATE pg_catalog."default",
h1(#     icp_id integer NOT NULL,
h1(#     CONSTRAINT app_meter_pkey PRIMARY KEY (id),
h1(#     CONSTRAINT app_meter_icp_id_004d0d3c_fk_app_icp_id FOREIGN KEY (icp_id)
h1(#         REFERENCES public.icps (id) MATCH SIMPLE
h1(#         ON UPDATE NO ACTION
h1(#         ON DELETE NO ACTION
h1(#         DEFERRABLE INITIALLY DEFERRED
h1(# );
CREATE TABLE
h1=# CREATE INDEX app_meter_icp_id_004d0d3c ON public.meters USING btree (icp_id) TABLESPACE pg_default;
CREATE INDEX
h1=# \q
$ psql h2
psql (11.5)
Type "help" for help.

h2=# create table public.icps (id integer not null primary key);
CREATE TABLE
h2=# CREATE TABLE public.meters
h2-# (
h2(#     id integer NOT NULL,
h2(#     "number" character varying(16) COLLATE pg_catalog."default",
h2(#     icp_id integer NOT NULL,
h2(#     CONSTRAINT app_meter_pkey PRIMARY KEY (id),
h2(#     CONSTRAINT app_meter_icp_id_004d0d3c_fk_app_icp_id FOREIGN KEY (icp_id)
h2(#         REFERENCES public.icps (id) MATCH SIMPLE
h2(#         ON UPDATE NO ACTION
h2(#         ON DELETE NO ACTION
h2(#         DEFERRABLE INITIALLY DEFERRED
h2(# );
CREATE TABLE
h2=# CREATE INDEX app_meter_icp_id_004d0d3c ON public.meters USING btree (icp_id) TABLESPACE pg_default;
CREATE INDEX
h2=# \q
$ ks --from postgresql://will@localhost/h1 --to postgresql://will@localhost/h2 --only meters --verbose --workers 4 --set-from-variables="timezone='Australia/Melbourne'"
Kitchen Sync
starting meters
finished meters in 0s using 0 hash commands and 0 rows commands changing 0 rows
committed in 0s
committed in 0s
committed in 0s
committed in 0s
Finished Kitchen Syncing.
```

**Comment by hsenot** [comment]
Thanks Will!

I tried replicating your step, and you're right, it does work as expected. The test case I submitted is not sufficient to identify a problem, apologies for that.

However, after running the DDLs in a fresh database as per your suggestion, I had a closer look at the **primary_key_lister** client query at https://github.com/willbryant/kitchen_sync/blob/master/src/ks_postgresql.cpp#L970-L976

Running that query manually for the _meters_ table in a fresh database returns both 'id' and 'icp_id', when I expected only 'id'.

There seem to be several ways primary keys can be identified in the schema system tables.
I found 2 alternative **primary_key_lister** client queries (that only returned 'id'):
1) modifying the **primary_key_lister** client query on https://github.com/willbryant/kitchen_sync/blob/master/src/ks_postgresql.cpp#L974 , replacing: `"information_schema.key_column_usage.table_name = information_schema.table_constraints.table_name AND "` by `"information_schema.key_column_usage.constraint_name = information_schema.table_constraints.constraint_name AND "`

2) using pg_index and pg_attribute tables as per https://wiki.postgresql.org/wiki/Retrieve_primary_key_columns

I recompiled ks after applying change 1. above in ks_postgresql.cpp, and all my tables are now synchronising perfectly ... and so fast :-)

Now, tbh I am not 100% sure this is an issue that affects others but I thought I'd flag our (local) solution.

In any case, thanks for this beautiful tool :-)

**Comment by willbryant** [comment]
Awesome, thanks for tracking that down!  Definitely the kind of confusing bug that needs fixing.  I've applied your fix and it'll be in the next release candidate tag.

ps. those nouns are horribly familiar...

**Comment by hsenot** [comment]
Fantastic, thanks Will! Very much appreciated!

And thx again for designing this tool, which we plan to make much more use of in the future ...

PS: those nouns are part of my work universe as I work at a progressive power retailer in Australia with a Kiwi parent company ;-)
