### ISSUE TITLE
New IDLE command is not backwards compatible

### ISSUE THREAD

**Issue by proby** [willbryant/kitchen_sync#82]
While trying to diagnose #81 I came across this.

To reproduce this you need
* The `from` worker is `v1.17` or below
* The `to` worker is `v2.0` or higher
* 2 or more workers (`--workers=2`)

The resulting error I get in the console:
```
Error in the 'from' worker: Unknown command 31
Error in the 'to' worker: Connection closed
```

The `IDLE` command was introduced in https://github.com/willbryant/kitchen_sync/commit/006972b56c9b736d4bcfef4e6691b8f62e849bd7. It seems like the `from` worker is trying to inform the `to` worker that it's `IDLE` but the `to` worker doesn't know about `IDLE` so it throws: https://github.com/willbryant/kitchen_sync/blob/f6184749878873d05f6b714a7b2d8a37e63e8f14/src/sync_from_protocol.h#L72

As semi-implied above an immediate mitigation is to set `--workers=1`. It's slow, but it works.

A few unvetted ideas off the top of my head (as I don't like raising problems without some idea of a solution):
* Make a `v1.x` fix that is aware of `IDLE` as a command but treats it as a no-op
* Make a `v2.x` fix that doesn't send `IDLE` if the other worker can't handle it
* Make a `v2.x` fix that has the `to` worker catch the error thrown from the `from` worker (`Unknown command 31`), ignore it, _not_ close its connection, and continue on with work

**Comment by willbryant** [comment]
Grr, this is totally believable, but I'm annoyed that it hasn't already been picked up by test cases.  test/Dockerfile-sync-v1 does use `--workers 2` specifically in the hopes of picking up this type of bug.

**Comment by proby** [comment]
Can comfirm 2a13634 resolves this issue for me.
