### ISSUE TITLE
ERROR:  type "double" does not exist LINE 5:   "startLatitude" double(8,2) NOT NULL,

### ISSUE THREAD

**Issue by martyzz1** [willbryant/kitchen_sync#88]
this should be DOUBLE PRECISION in postgres?

**Comment by martyzz1** [comment]
ok further investigation seems this occurs if the definition is

double(8,2)

But it works correctly if the definition is

double

**Comment by willbryant** [comment]
Hmm it is `double precision` in the postgresql part of codebase: https://github.com/willbryant/kitchen_sync/blob/master/src/ks_postgresql.cpp#L502 https://github.com/willbryant/kitchen_sync/blob/master/src/ks_postgresql.cpp#L774

So I think the bug must be in interpreting your source schema, which is mysql right?  I'll try and add a test case to reproduce it.

**Comment by willbryant** [comment]
https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html
>As of MySQL 8.0.17, the nonstandard FLOAT(M,D) and DOUBLE(M,D) syntax is deprecated and support for it will be removed in a future MySQL version.

I guess I need to support it in the meantime though.

**Comment by willbryant** [comment]
Fixed in v2.5, thanks for reporting.

**Comment by martyzz1** [comment]
Thanks
