### ISSUE TITLE
password contain @ not support

### ISSUE THREAD

**Issue by eeokee** [willbryant/kitchen_sync#89]
please help!

ks --from mysql://dev:life@2019@192.168.0.251:3306/xxl-job    --to mysql://root:root@192.168.1.189:3307/xxl-job2

![image](https://user-images.githubusercontent.com/3079825/92588331-6a10f300-f2cb-11ea-9849-31fa7084503a.png)

**Comment by willbryant** [comment]
It's a normal URL so you can URL-encode the @:

`ks --from mysql://dev:life%402019@192.168.0.251:3306/xxl-job --to mysql://root:root@192.168.1.189:3307/xxl-job2`
