### ISSUE TITLE
Error in the 'to' worker: MySQL server has gone away

### ISSUE THREAD

**Issue by javier-sanz** [willbryant/kitchen_sync#92]
I am trying to sync to tables between two MySQL databases version 5.7. One is on the cloud and the other one is locally running on a docker container inside a MacOS. KS is running on the same Mac and it has been installed using brew. KS version is 2.5. This happens when either I create the table or I use the `--alter` option. The log with `--debug` option is:

```
Kitchen Sync
from command: ks_mysql from 127.0.0.1 13310 prod root - -
1601453467.791145 worker 0 starting order
1601453467.791177 worker 0 <- range order
1601453475.097127 worker 0 -> range order (15250640) (15850979)
1601453475.101197 worker 0 <- rows order (NULL) (15850979)
1601453507.190109 worker 0 -> rows order (NULL) (15850979)
Error in the 'to' worker: MySQL server has gone away
REPLACE INTO `order` (`id`, `company_id`, `fk_r_network_customers_id`, `store_id`, `return_code`, `customer_id`, `rma`, `status`, `is_test`, `carrier`, `carrier_rates`, `label_amount`, `shippi...
Error in the 'from' worker: Couldn't write to descriptor: Broken pipe
```

Using `--alter` I can see that `int(11) unsigned NOT NULL` rows become `int unsigned NOT NULL`. Extracting the DDL of the created table with DBeaver those rows are underneath `int(10) unsigned NOT NULL`. The other thing I can see is different is the encoding. We use `DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci` but on the `--alter`creation is not specified so all varchars rows become `COLLATE utf8_unicode_ci` 

I don't know if there is a way to get more log so I can give you more info.

**Comment by willbryant** [comment]
This usually means mysql is crashing or is killing the connection because of an error. The schema things are because KS doesn't know all the database-specific stuff but aren't very likely cause this kind of problem.

I think you probably want to see the mysql error log at the 'to' end ie. the one inside your container. Depending on whose docker image you are using this could be either visible in the docker logs for the container, or you might need to docker exec in to see error logfiles.

**Comment by javier-sanz** [comment]
You were right. From the log inside the container:

`2020-09-30T08:11:53.026262Z 206 [Note] Aborted connection 206 to db: 'orders' user: 'root' host: '172.17.0.1' (Got a packet bigger than 'max_allowed_packet' bytes)`

[This did the trick](https://stackoverflow.com/questions/93128/mysql-error-1153-got-a-packet-bigger-than-max-allowed-packet-bytes)

Thanks a lot for your very fast reply.
