### ISSUE TITLE
Unique index names for PostgreSQL

### ISSUE THREAD

**Issue by easeev** [willbryant/kitchen_sync#95]
I'm syncing MySQL to PostgreSQL and having a problem with the same index names on different tables which is apparently allowed in MySQL and [not allowed in PostgreSQL](https://stackoverflow.com/questions/26997441/why-cant-two-tables-have-an-index-of-the-same-name):

```
Kitchen Sync

...

CREATE TABLE "public"."assessment_assessmentfeedback" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "submission_uuid" character varying(128) NOT NULL,
  "feedback_text" text NOT NULL,
  PRIMARY KEY("id"))
CREATE UNIQUE INDEX "submission_uuid" ON "public"."assessment_assessmentfeedback" ("submission_uuid")

...

CREATE TABLE "public"."assessment_peerworkflow" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "student_id" character varying(40) NOT NULL,
  "item_id" character varying(128) NOT NULL,
  "course_id" character varying(255) NOT NULL,
  "submission_uuid" character varying(128) NOT NULL,
  "created_at" timestamp without time zone NOT NULL,
  "completed_at" timestamp without time zone,
  "grading_completed_at" timestamp without time zone,
  "cancelled_at" timestamp without time zone,
  PRIMARY KEY("id"))
CREATE UNIQUE INDEX "submission_uuid" ON "public"."assessment_peerworkflow" ("submission_uuid")
ERROR:  relation "submission_uuid" already exists

CREATE UNIQUE INDEX "submission_uuid" ON "public"."assessment_peerworkflow" ("submission_uuid")
Kitchen Syncing failed.
```

Are there any possible workarounds?

**Comment by willbryant** [comment]
Yeah, this should almost be documented somewhere a FAQ. It's something that MySQL/MariaDB supports and PostgreSQL doesn't, so ultimately, the index is going to need to be renamed.

The easiest solution, which is what reporters of previous issues have done, is to rename it in the source database, like this:
```
ALTER TABLE assessment_assessmentfeedback RENAME INDEX submission_uuid TO assessment_assessmentfeedback_ submission_uuid;
```

In principle this could be done in the schema translation code in KS and I'm not opposed to doing this. The problem is deciding when users would expect it to be done, what they should be renamed to given the name length constraints in PostgreSQL, etc.

**Comment by willbryant** [comment]
I think I'm leaning towards having KS add a suffix number to the end of the index name if there are name collisions, so in this example `assessment_assessmentfeedback` might win the name `submission_uuid` and `assessment_peerworkflow` would get `submission_uuid2`. Sort of ugly, but prefixing with table names etc. is sometimes going to produce too-long names, and some people like a standard prefix (eg. `idx_` or `index_`). And if users want nicer looking names, they can always rename in the source schema.

**Comment by easeev** [comment]
> I think I'm leaning towards having KS add a suffix number to the end of the index name if there are name collisions, so in this example `assessment_assessmentfeedback` might win the name `submission_uuid` and `assessment_peerworkflow` would get `submission_uuid2`. Sort of ugly, but prefixing with table names etc. is sometimes going to produce too-long names, and some people like a standard prefix (eg. `idx_` or `index_`). And if users want nicer looking names, they can always rename in the source schema.

Yeah, that's exactly what I was thinking.
